# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#many-hooks-parallelism for more info about parallelism-ci-cpu-cores
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
        exclude: devcontainer/devcontainer.json
      - id: pretty-format-json
        args: [--indent, "2", --autofix]
        exclude: (^templates/|devcontainer/devcontainer.json)
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key

    # Prettier is an opinionated code formatter.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        exclude: '(\.terraform|\.md)$'

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        args: ["-x"]
        exclude: (\.(zsh|zshrc)$|^\.devcontainer/dotfiles/)

  # Secret scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
